//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clock
    {
        public long id { get; set; }
        public long workerId { get; set; }
        public long shiftId { get; set; }
        public System.DateTime startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
    
        public virtual Shift Shift { get; set; }
        public virtual User User { get; set; }
    }
}
