//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Company
    {
        [NotMapped]
        public long id { get; set; }
        public string name { get; set; }
        public long ownerID { get; set; }
        public string logoUrl { get; set; }
        public string description { get; set; }
    
        public virtual User owner { get; set; }
    }
}
