//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Easy2MEntities : DbContext
    {
        public Easy2MEntities()
            : base("name=Easy2MEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Clock> Clocks { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<workerCompany> workerCompanies { get; set; }
        public virtual DbSet<ShiftsBoard> ShiftsBoards { get; set; }
        public virtual DbSet<ShiftRequest> ShiftRequests { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<WorkerReport> WorkerReports { get; set; }
    }
}
