//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public long roleId { get; set; }
        public long companyId { get; set; }
        public string roleName { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
