//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftRequest
    {
        public long shiftId { get; set; }
        public int week { get; set; }
        public int year { get; set; }
        public long workerId { get; set; }
    
        public virtual ShiftBoard Shift { get; set; }
        public virtual User User { get; set; }
    }
}
