//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerReport
    {
        public long reportId { get; set; }
        public long workerId { get; set; }
        public long companyId { get; set; }
        public System.DateTime date { get; set; }
        public string url { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
